### ISSUE TITLE
Doesn't work with react 0.14

### ISSUE THREAD

**Issue by goldensunliu** [onefinestay/react-daterange-picker#82]
on https://github.com/onefinestay/react-daterange-picker/blob/master/src/DateRangePicker.jsx#L22
``` javascript
React.initializeTouchEvents(true);
```
is called

with React v 0.14

```
React.initializeTouchEvents is no longer necessary and has been removed completely. 
Touch events now work automatically.
```

**Comment by AlanFoster** [comment]
For visibility #79 Plans to deal with this issue.

**Comment by goldensunliu** [comment]
is this ready to be closed?

**Comment by nikulinsanya** [comment]
I still get several errors with react 0.14
Warning: require('react/addons') is deprecated. Access using require('react-addons-{addon}') 
DateRangePicker.js:59 Uncaught TypeError: _reactAddons2.default.initializeTouchEvents is not a function

**Comment by goldensunliu** [comment]
@nikulinsanya are you sure you have done a clean 'npm install'? You will see those if your react dependency is out dated.

**Comment by AlanFoster** [comment]
This should be resolved now, thanks to the [v1.0.0 release](https://github.com/onefinestay/react-daterange-picker/releases/tag/v1.0.0)
